### PR TITLE
Compatible with both Python 2 and 3

### PR DESCRIPTION
**Pull request by voletiv**
Hello,

I have modified the code to be compatible with both Python2 and Python3. The following are all the changes I made:
- Ran the codes through a Pep8 Linter to make code compatible with pep8 (spaces to tabs, spaces around arithmetic operators, etc.)
- Changed "import cPickle" to "from six.moves import cPickle" to be compatible with Python 2 and 3
- Change print statements from "print 'blah blah'" to "print("blah blah")"
- Changed order of imports to alphabetical in every code
- Changed some divisions from '/' to '//' so as to get integer output, to be compatible with both python versions
- Added requirements.txt files for Python2 and Python3
- Appended .gitignore file with lines from git's standard .gitignore file for Python

I have tested the code for both Python2 and Python3, seems to be working well. I ran the same codes as mentioned in your Wiki and got the same files saved and the same graphs generated.

Let me know if you face any problems! :)

Regards,
Vikram

### CODE REVIEW

**Comment by voletiv** [comment]
Hi,

In addition, I have also incorporated the last 3 pull requests' changes in my code, since they were mostly beautification. The changes are:
1) @JPery 's pull request: Fixed issue where training an HMM model from di…
2) @lmcmenemie 's pull request: readme: fix various broken links
3) @fnaser 's pull request: beautified featureAndTrain

Regards,
Vikram

**Comment by itaiariel-es** [comment]
Hi,
I tried to use your branch.
It works for me on ubuntu.
in the file `audioSegmentation.py` I had to change 
`f = open(gtFile, "rb")`
into
`f = open(gtFile, "rt")`
so it will read the file as text (line 153)

**Comment by cchara11** [comment]
Any update on Windows?

**Comment by voletiv** [comment]
Hi @cchara11 ,

Sorry, I'm not working on Windows at the moment, the changes I made worked in Ubuntu 16.04. Maybe there are some library dependency issues between Ubuntu and Windows?

@itaiariel-es I didn't change anything there, "rb" was retained from the original repo. Thank you for confirming it works in Ubuntu!

**Comment by VictorGaiva** [comment]
Looking forward for this pull being approved

**Comment by voletiv** [comment]
@VictorGaiva You could fork from my repo: https://github.com/voletiv/pyAudioAnalysis

**Pull request closed without merging**
